name: Hello World selfhosted
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-TEST_github_selfhosted_runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"