name: Hello World selfhosted
on: [push]
jobs:
  Hello-World-Job-aws-selfhosted:
    runs-on:
      - codebuild-test-github-actions-selfhosted-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"